name: My First Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Show my machine
        run: |
          echo "Running on:"
          hostname
          echo "User:"
          whoami
          echo "Operating system:"
          uname -a

      - name: Run Python
        run: python3 hello.py
